export const tasksList = [
  {
    "id": 1,
    "title": "mapで商品名リスト作成",
    "problem": "商品オブジェクト配列から name だけを取り出した新しい配列を作ってください。",
    "level": "初級",
    "topic": "array",
    "duration": "5分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 2,
    "title": "reduceで売上合計",
    "problem": "注文金額配列 [1200, 800, 1500] の合計を reduce で計算してください。",
    "level": "初級",
    "topic": "reduce",
    "duration": "5分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 3,
    "title": "try/catchでJSON検証",
    "problem": "文字列が有効なJSONか判定する isValidJSON(text) を作ってください。",
    "level": "初級",
    "topic": "try...catch",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 4,
    "title": "toISOStringでUTC化",
    "problem": "Dateオブジェクトを UTC の ISO 文字列へ変換する関数を作成してください。",
    "level": "初級",
    "topic": "Date",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 5,
    "title": "map + parseInt罠回避",
    "problem": "['10', '11', '12'] を数値配列に変換してください。map(parseInt) を使わないこと。",
    "level": "中級",
    "topic": "array",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 6,
    "title": "Promise.all同時実行",
    "problem": "fetchProfile() と fetchNotifications() を並列で待ち、結果を { profile, notifications } で返してください。",
    "level": "中級",
    "topic": "Promise",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 7,
    "title": "Fetchのokチェック",
    "problem": "fetchでJSON取得時、response.ok が false なら Error を throw する fetchJSON(url) を作ってください。",
    "level": "中級",
    "topic": "Fetch",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 8,
    "title": "Intl.NumberFormat通貨表示",
    "problem": "金額123456.789を ja-JP / JPY の通貨形式で表示する formatYen(value) を作成してください。",
    "level": "中級",
    "topic": "Intl",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 9,
    "title": "reduceの初期値設計",
    "problem": "空配列でも落ちない maxOrNull(numbers) を reduce で実装し、空なら null を返してください。",
    "level": "上級",
    "topic": "reduce",
    "duration": "15分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 10,
    "title": "Promise.all fail-fast対策",
    "problem": "Promise.allで全結果を取得したいです。各Promiseを失敗しても結果配列に残る形へ変換してください。",
    "level": "上級",
    "topic": "Promise",
    "duration": "18分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 11,
    "title": "Fetchキャンセル処理",
    "problem": "3秒で自動中断する fetchWithTimeout(url, ms) を AbortController で実装してください。",
    "level": "上級",
    "topic": "Fetch",
    "duration": "20分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 12,
    "title": "エラー分類して再throw",
    "problem": "RangeErrorだけ握りつぶし、それ以外は再throwする executeSafely(fn) を作成してください。",
    "level": "上級",
    "topic": "try...catch",
    "duration": "15分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 13,
    "title": "ダッシュボード初期取得",
    "problem": "ユーザー情報・案件一覧・通知を同時取得し、いずれか失敗時はログを残して空配列でフォールバックしてください。",
    "level": "実務",
    "topic": "Promise + Fetch",
    "duration": "25分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 14,
    "title": "APIレスポンス正規化",
    "problem": "注文API配列を [{ id, total, createdAtISO }] へ整形し、総額を同時に返す normalizeOrders を作ってください。",
    "level": "実務",
    "topic": "map + reduce",
    "duration": "25分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 15,
    "title": "金額表示ユーティリティ",
    "problem": "localeとcurrencyを引数で受ける formatMoney(value, locale, currency) を作成してください。",
    "level": "実務",
    "topic": "Intl",
    "duration": "20分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 16,
    "title": "finallyでローディング解除",
    "problem": "非同期処理で成功/失敗に関係なく loading を false に戻す submitForm を実装してください。",
    "level": "実務",
    "topic": "try...catch...finally",
    "duration": "18分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 17,
    "title": "filterで有効データ抽出",
    "problem": "users配列から isActive が true の要素だけを抽出して activeUsers を作成してください。",
    "level": "初級",
    "topic": "filter",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 18,
    "title": "allSettledで結果一覧化",
    "problem": "複数API呼び出しを allSettled で待ち、fulfilled と rejected の件数を返す集計関数を作ってください。",
    "level": "中級",
    "topic": "Promise.allSettled",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 19,
    "title": "URLSearchParamsでGETクエリ作成",
    "problem": "keyword と page を受け取り、/search?keyword=...&page=... 形式のURL文字列を返してください。",
    "level": "中級",
    "topic": "URLSearchParams",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 20,
    "title": "filterで入力検証クリーニング",
    "problem": "オブジェクト配列から id が有限数かつ 0 でない要素だけ残す sanitizeItems(items) を作成してください。",
    "level": "上級",
    "topic": "filter",
    "duration": "15分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 21,
    "title": "allSettledで障害時フォールバック",
    "problem": "user/task/notice の3APIを allSettled で処理し、失敗した項目だけデフォルト値を入れて返してください。",
    "level": "上級",
    "topic": "Promise.allSettled",
    "duration": "18分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 22,
    "title": "URLSearchParams複数値対応",
    "problem": "tags配列を重複キーでクエリ化する buildProductQuery({ keyword, tags }) を実装してください。",
    "level": "実務",
    "topic": "URLSearchParams",
    "duration": "22分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 23,
    "title": "forEachで副作用ログ収集",
    "problem": "orders配列をforEachで走査し、idだけを logs 配列へ push してください。",
    "level": "初級",
    "topic": "forEach",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 24,
    "title": "flatMapでネスト配列展開",
    "problem": "users配列から全ユーザーのrolesを1次元配列にしてください。",
    "level": "中級",
    "topic": "flatMap",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 25,
    "title": "findで1件取得",
    "problem": "productsから id === 3 の商品を1件取得してください。",
    "level": "初級",
    "topic": "find",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 26,
    "title": "findIndexで位置取得",
    "problem": "emails配列で support@example.com のindexを取得してください。",
    "level": "初級",
    "topic": "findIndex",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 27,
    "title": "includes/some/every判定",
    "problem": "tagsに \"vue\" が含まれるか、scoresに60以上が1つでもあるか、全員18歳以上かを判定してください。",
    "level": "中級",
    "topic": "includes + some + every",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 28,
    "title": "sortとtoSortedの違い",
    "problem": "numbersを昇順に並べつつ、元配列を壊さない sortedCopy を作成してください。",
    "level": "中級",
    "topic": "sort + toSorted",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 29,
    "title": "reverseとtoReversedの違い",
    "problem": "arrを逆順コピーしつつ、元arrを保持する reversedCopy を作ってください。",
    "level": "中級",
    "topic": "reverse + toReversed",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 30,
    "title": "sliceとspliceの使い分け",
    "problem": "itemsから先頭2件をsliceでコピーし、別配列targetのindex1へ\"X\"をspliceで挿入してください。",
    "level": "中級",
    "topic": "slice + splice",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 31,
    "title": "concatとflatで配列加工",
    "problem": "a,bを結合し、nestedを1段平坦化した配列を作成してください。",
    "level": "初級",
    "topic": "concat + flat",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 32,
    "title": "push/pop/shift/unshift基礎",
    "problem": "queue配列の末尾追加・末尾削除・先頭削除・先頭追加を順に実装してください。",
    "level": "初級",
    "topic": "push + pop + shift + unshift",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 33,
    "title": "Object.keys/values/entries",
    "problem": "profileオブジェクトからkey配列・value配列・entry配列を取得してください。",
    "level": "初級",
    "topic": "Object.keys + Object.values + Object.entries",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 34,
    "title": "fromEntriesで再オブジェクト化",
    "problem": "entries配列をオブジェクトへ戻し、nameだけ大文字化してください。",
    "level": "中級",
    "topic": "Object.fromEntries",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 35,
    "title": "assignとスプレッドでマージ",
    "problem": "baseとpatchをマージし、nameだけ\"new\"に上書きしたオブジェクトを2通りで作成してください。",
    "level": "中級",
    "topic": "Object.assign + spread",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": "参照更新の注意あり",
    "mutationWarningLevel": "caution"
  },
  {
    "id": 36,
    "title": "hasOwnPropertyで所有確認",
    "problem": "userが own property として \"email\" を持つか判定してください。",
    "level": "初級",
    "topic": "hasOwnProperty",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 37,
    "title": "String検索メソッドセット",
    "problem": "textに\"vue\"を含むか、\"Hello\"で始まるか、\"!\"で終わるか判定してください。",
    "level": "初級",
    "topic": "includes + startsWith + endsWith",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 38,
    "title": "split/join/trim/大小文字変換",
    "problem": "\"  Vue,React,Angular  \" をtrim後に分割し、すべて小文字で \"|\" 連結してください。",
    "level": "初級",
    "topic": "split + join + trim + toLowerCase + toUpperCase",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 39,
    "title": "replaceとreplaceAllの使い分け",
    "problem": "message内の最初の\"-\"だけ置換した結果と、全\"-\"置換の結果を作成してください。",
    "level": "中級",
    "topic": "replace + replaceAll",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 40,
    "title": "Promise.thenで後続処理",
    "problem": "fetchUserName() の結果を then で受け取り、\"USER: \" を付けて返してください。",
    "level": "初級",
    "topic": "Promise.then",
    "duration": "8分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 41,
    "title": "setTimeout/setInterval制御",
    "problem": "1秒ごとにcountを増やし、5秒後に停止するタイマーを実装してください。",
    "level": "中級",
    "topic": "setTimeout + setInterval",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 42,
    "title": "Number/parseInt/parseFloat変換",
    "problem": "\"42\" と \"3.14\" をそれぞれ数値化し、整数/小数を使い分けてください。",
    "level": "初級",
    "topic": "Number + parseInt + parseFloat",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 43,
    "title": "Math丸めと乱数",
    "problem": "value=3.6 の切り捨て/切り上げ/四捨五入と、1〜10の乱数整数を作成してください。",
    "level": "初級",
    "topic": "Math.floor + Math.ceil + Math.round + Math.random",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 44,
    "title": "Date取得メソッド基礎",
    "problem": "現在日付から年/月/日を取得し、YYYY-M-D形式文字列を作成してください。",
    "level": "初級",
    "topic": "new Date + getFullYear + getMonth + getDate",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 45,
    "title": "JSON stringify/parse往復",
    "problem": "payloadオブジェクトをJSON文字列化し、再度オブジェクトへ戻してください。",
    "level": "初級",
    "topic": "JSON.stringify + JSON.parse",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 46,
    "title": "typeof/isArray/instanceof判定",
    "problem": "valueが文字列か、listが配列か、errがErrorインスタンスか判定してください。",
    "level": "中級",
    "topic": "typeof + Array.isArray + instanceof",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 47,
    "title": "ES6実務構文セット",
    "problem": "userからnameを分割代入し、新配列をspreadで作り、ネスト名を optional chaining + ?? で安全取得してください。",
    "level": "実務",
    "topic": "destructuring + spread + optional chaining + nullish coalescing",
    "duration": "15分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 48,
    "title": "Map/Set基礎運用",
    "problem": "Mapへ key/value を保存して取得し、配列の重複を Set で削除してください。",
    "level": "実務",
    "topic": "Map + Set",
    "duration": "15分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 49,
    "title": "実務コンボ: API取得→filter→map",
    "problem": "users APIを取得し、isActiveなユーザーのname配列だけ返す loadActiveUserNames を実装してください。",
    "level": "実務",
    "topic": "fetch + filter + map",
    "duration": "18分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 50,
    "title": "実務コンボ: fetcher + エラーハンドリング",
    "problem": "fetcher(url)を作成し、ok判定失敗で Error を投げ、呼び出し側で try/catch してください。",
    "level": "実務",
    "topic": "fetch + async/await + try/catch",
    "duration": "18分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 51,
    "title": "実務コンボ: reduceグループ化 + 重複排除",
    "problem": "usersをroleごとにグループ化し、全role一覧は重複排除して返してください。",
    "level": "上級",
    "topic": "reduce + Set",
    "duration": "20分",
    "starDifficulty": 2,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 52,
    "title": "実務コンボ: インクリメンタル検索 + debounce",
    "problem": "name検索を大文字小文字無視で実装し、debounceでAPI連打を防いでください。",
    "level": "実務",
    "topic": "filter + includes + toLowerCase + debounce",
    "duration": "22分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 53,
    "title": "実務コンボ: 非破壊ソート + 1件取得 + 安全アクセス",
    "problem": "usersを年齢昇順で非破壊ソートし、targetIdユーザーのprofile.nameを安全取得してください。",
    "level": "上級",
    "topic": "toSorted + find + optional chaining + nullish",
    "duration": "20分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 54,
    "title": "実務コンボ: フォーム送信JSON化 + 条件付きプロパティ",
    "problem": "nameは必須、ageはある時だけ含めるpayloadを作り、POST送信してください。",
    "level": "実務",
    "topic": "fetch + JSON.stringify + spread",
    "duration": "18分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 55,
    "title": "実務コンボ: クエリ取得 + クエリ生成",
    "problem": "location.searchからid取得し、/api/users?page=2 のURLをURL APIで生成してください。",
    "level": "実務",
    "topic": "URLSearchParams + URL",
    "duration": "18分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 56,
    "title": "実務コンボ: structuredClone + セキュア分割代入",
    "problem": "userをディープコピーしてpasswordを除外した safeUser を作成してください。",
    "level": "上級",
    "topic": "structuredClone + destructuring rest",
    "duration": "16分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 57,
    "title": "実務コンボ: Promise.all並列 + loading finally",
    "problem": "users/postsを並列取得し、loadingを必ずfalseへ戻す loadPageData を作成してください。",
    "level": "実務",
    "topic": "Promise.all + try/finally",
    "duration": "20分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 58,
    "title": "実務コンボ: fromEntries + Map + flatMap",
    "problem": "usersからidキーobjectとMapを作成し、postsからtags一覧をflatMapで抽出してください。",
    "level": "実務",
    "topic": "Object.fromEntries + Map + flatMap",
    "duration": "22分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 59,
    "title": "実務コンボ: with/at/条件付き配列追加",
    "problem": "arrのindex更新を非破壊で行い、末尾取得し、isAdmin時のみadminItemsを追加してください。",
    "level": "上級",
    "topic": "with + at + spread",
    "duration": "18分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 60,
    "title": "実務コンボ: every/some + localStorage保存復元",
    "problem": "usersの全active判定とadmin存在判定を行い、userをlocalStorageへ保存して復元してください。",
    "level": "実務",
    "topic": "every + some + localStorage + JSON",
    "duration": "18分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 61,
    "title": "配列の平均値を出す",
    "problem": "scores配列の平均値を返す calcAverage(scores) を作成してください。",
    "level": "初級",
    "topic": "reduce",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 62,
    "title": "文字列をキャメルケース化",
    "problem": "\"user profile name\" を userProfileName に変換してください。",
    "level": "初級",
    "topic": "split + map + join",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 63,
    "title": "ID配列をCSVへ",
    "problem": "users配列からidを取り出して \"1,2,3\" 形式で返してください。",
    "level": "初級",
    "topic": "map + join",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 64,
    "title": "roleごとの人数を集計",
    "problem": "users配列から role ごとの件数オブジェクトを作成してください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 65,
    "title": "配列の差分を作る",
    "problem": "aにあってbにない値だけを返す diff(a, b) を作成してください。",
    "level": "中級",
    "topic": "filter + includes",
    "duration": "10分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 66,
    "title": "URLから複数パラメータ取得",
    "problem": "search文字列から page と sort を取得しオブジェクトで返してください。",
    "level": "中級",
    "topic": "URLSearchParams",
    "duration": "12分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 67,
    "title": "任意キーでソート関数生成",
    "problem": "keyを受けてオブジェクト配列を昇順ソートする sortBy(list, key) を作ってください。",
    "level": "中級",
    "topic": "toSorted",
    "duration": "14分",
    "starDifficulty": 1,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 68,
    "title": "allSettledの失敗理由だけ抽出",
    "problem": "promises実行後、rejectedのreasonだけ配列で返してください。",
    "level": "上級",
    "topic": "Promise.allSettled",
    "duration": "16分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 69,
    "title": "deep copy後に安全更新",
    "problem": "userをdeep copyし、profile.nameだけ更新した新オブジェクトを返してください。",
    "level": "上級",
    "topic": "structuredClone + spread",
    "duration": "16分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 70,
    "title": "正常系だけMap化",
    "problem": "activeなusersのみを id => user のMapにしてください。",
    "level": "上級",
    "topic": "filter + Map",
    "duration": "14分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 71,
    "title": "ページングURLビルダー",
    "problem": "baseUrl, page, limit を受けてページングURLを返す関数を作ってください。",
    "level": "実務",
    "topic": "URL + URLSearchParams",
    "duration": "18分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 72,
    "title": "フィルタ条件をクエリ化",
    "problem": "filtersオブジェクトの空値を除外し、クエリ文字列を返してください。",
    "level": "実務",
    "topic": "Object.entries + URLSearchParams",
    "duration": "18分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 73,
    "title": "APIレスポンス正規化v2",
    "problem": "rawUsersを {id, name, city} 配列へ変換し、city欠損時は\"unknown\"にしてください。",
    "level": "実務",
    "topic": "map + optional chaining + nullish",
    "duration": "20分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 74,
    "title": "タグ検索の前処理",
    "problem": "入力文字列を正規化してタグ配列にし、空要素を除去してください。",
    "level": "中級",
    "topic": "trim + toLowerCase + split + filter",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 75,
    "title": "遅延保存のdebounceラッパー",
    "problem": "save関数をdebounceする createDebouncedSave(save, delay) を作ってください。",
    "level": "上級",
    "topic": "setTimeout + clearTimeout",
    "duration": "16分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 76,
    "title": "配列の最後から2番目",
    "problem": "arrの最後から2番目の要素を安全に返してください。なければnull。",
    "level": "上級",
    "topic": "at",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 77,
    "title": "withで非破壊置換",
    "problem": "arrのindex位置だけnewValueに差し替えた新配列を返してください。",
    "level": "中級",
    "topic": "with",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 78,
    "title": "localStorageセーフ読み込み",
    "problem": "keyを受けてJSONを安全に復元し、失敗時はfallbackを返す関数を作成してください。",
    "level": "実務",
    "topic": "localStorage + JSON.parse + try/catch",
    "duration": "14分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 79,
    "title": "Promise.allで依存なし先読み",
    "problem": "profile/settings/notifications を並列取得して1つのオブジェクトで返してください。",
    "level": "実務",
    "topic": "Promise.all + fetch",
    "duration": "18分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 80,
    "title": "条件付き更新payload作成",
    "problem": "name必須、emailとphoneは値がある時のみ含めるpayloadを作って返してください。",
    "level": "実務",
    "topic": "spread + nullish + Boolean",
    "duration": "16分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 81,
    "title": "マッチング候補スコア付け",
    "problem": "candidatesに対して score を計算し、高い順で返す rankCandidates(candidates) を作ってください。",
    "level": "実務",
    "topic": "map + sort",
    "duration": "18分",
    "starDifficulty": 5,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 82,
    "title": "ストリーミング差分反映",
    "problem": "既存itemsへupdates差分を適用して最新配列を返す mergeStreamItems(items, updates) を作ってください。",
    "level": "上級",
    "topic": "Map + forEach",
    "duration": "16分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 83,
    "title": "決済金額の端数処理",
    "problem": "小数金額を最小通貨単位(整数)へ変換する toMinorUnit(amount) を作ってください。",
    "level": "中級",
    "topic": "Math + Number",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 84,
    "title": "AI応答のJSON安全抽出",
    "problem": "AI文字列応答からJSONを抽出し、失敗時はnullを返す parseAiJson(text) を作ってください。",
    "level": "上級",
    "topic": "try...catch + JSON.parse",
    "duration": "14分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 85,
    "title": "ページングカーソル作成",
    "problem": "cursorとlimitから /api/feed?cursor=...&limit=... を作る buildCursorUrl(cursor, limit) を作ってください。",
    "level": "中級",
    "topic": "URLSearchParams",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 86,
    "title": "Webhook署名ヘッダー生成",
    "problem": "timestampとsignatureから `t=...,v1=...` を返す buildSignatureHeader を作ってください。",
    "level": "中級",
    "topic": "template literal",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 87,
    "title": "在庫の安全減算",
    "problem": "対象idの在庫をqtyだけ減らし、0未満にしない decreaseStock(items, id, qty) を作ってください。",
    "level": "中級",
    "topic": "map + Math.max",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 88,
    "title": "監査ログ整形",
    "problem": "logsを { actor, action, atISO } へ変換する normalizeAudit(logs) を作ってください。",
    "level": "初級",
    "topic": "map + toISOString",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 89,
    "title": "feature flag適用",
    "problem": "flags配列を { key: enabled } 形式へ変換する toFlagMap(flags) を作ってください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 90,
    "title": "支払い手段の優先選択",
    "problem": "isDefault優先、同率ならupdatedAt新しい順で先頭を返す pickPrimaryMethod(methods) を作ってください。",
    "level": "上級",
    "topic": "find + sort",
    "duration": "14分",
    "starDifficulty": 5,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 91,
    "title": "レート制限待機",
    "problem": "ms待機する sleep(ms) をPromiseで作成してください。",
    "level": "初級",
    "topic": "Promise + setTimeout",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 92,
    "title": "CSV行パース",
    "problem": "1行CSVを分割し空白除去する parseCsvLine(line) を作ってください。",
    "level": "中級",
    "topic": "split + trim",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 93,
    "title": "通貨別合計集計",
    "problem": "paymentsを通貨コード単位で合計する sumByCurrency(payments) を作ってください。",
    "level": "上級",
    "topic": "reduce",
    "duration": "16分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 94,
    "title": "検索候補ハイライト",
    "problem": "text内のkeyword一致部分を <mark>...</mark> で囲う highlight(text, keyword) を作ってください。",
    "level": "中級",
    "topic": "replace + RegExp",
    "duration": "14分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 95,
    "title": "APIレスポンス時間測定",
    "problem": "非同期関数fnの実行時間(ms)を返す measureAsync(fn) を作ってください。",
    "level": "中級",
    "topic": "performance.now",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 96,
    "title": "AIトークン上限トリム",
    "problem": "文字列をmaxChars以内に切り詰める trimPrompt(prompt, maxChars) を作ってください。",
    "level": "中級",
    "topic": "slice",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 97,
    "title": "冪等キー生成",
    "problem": "prefixとuserIdから冪等キーを作る buildIdempotencyKey(prefix, userId) を作ってください。",
    "level": "中級",
    "topic": "template literal + Date.now",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 98,
    "title": "価格帯フィルタ",
    "problem": "productsから min <= price <= max の要素のみ返す filterByPriceRange を作ってください。",
    "level": "初級",
    "topic": "filter",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 99,
    "title": "不要キー除外",
    "problem": "objから値がnull/undefinedのキーを除外する compactObject(obj) を作ってください。",
    "level": "中級",
    "topic": "Object.entries + fromEntries",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 100,
    "title": "並列取得と部分失敗通知",
    "problem": "API群をallSettledで実行し、成功データ配列と失敗件数を返す collectDataWithErrors を作ってください。",
    "level": "実務",
    "topic": "Promise.allSettled",
    "duration": "18分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 101,
    "title": "nullish coalescingで既定値",
    "problem": "valueがnull/undefinedのときだけfallbackを返す withFallback(value, fallback) を作ってください。",
    "level": "初級",
    "topic": "??",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 102,
    "title": "optional chainingで安全参照",
    "problem": "user.profile.name を安全に取得し、なければ \"guest\" を返す getUserName(user) を作ってください。",
    "level": "初級",
    "topic": "?.",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 103,
    "title": "重複除去ユーティリティ",
    "problem": "文字列配列の重複を除いた新配列を返す uniqueStrings(items) を作ってください。",
    "level": "中級",
    "topic": "Set",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 104,
    "title": "groupByでカテゴリ集計",
    "problem": "itemsを category ごとの配列にまとめる groupByCategory(items) を作ってください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 105,
    "title": "文字列パディング",
    "problem": "番号を4桁ゼロ埋めする formatCode(n) を作ってください。",
    "level": "初級",
    "topic": "padStart",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 106,
    "title": "配列をチャンク分割",
    "problem": "arrをsizeごとに分割した2次元配列を返す chunk(arr, size) を作ってください。",
    "level": "中級",
    "topic": "for + slice",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 107,
    "title": "日時フォーマット(YYYY-MM-DD)",
    "problem": "Dateを YYYY-MM-DD 形式の文字列へ変換する formatDate(date) を作ってください。",
    "level": "初級",
    "topic": "Date",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 108,
    "title": "配列の差分抽出",
    "problem": "aからbに含まれない要素だけ返す diff(a, b) を作ってください。",
    "level": "中級",
    "topic": "filter + Set",
    "duration": "10分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 109,
    "title": "真偽値の件数カウント",
    "problem": "flags配列のtrueの数を返す countTrue(flags) を作ってください。",
    "level": "初級",
    "topic": "filter",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 110,
    "title": "ソートキーを複数条件で比較",
    "problem": "usersを age昇順、同年齢はname昇順で並べる sortUsers(users) を作ってください。",
    "level": "中級",
    "topic": "sort",
    "duration": "12分",
    "starDifficulty": 2,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 111,
    "title": "includesで禁止語判定",
    "problem": "textに禁止語badが含まれるか返す hasBadWord(text) を作ってください。",
    "level": "初級",
    "topic": "includes",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 112,
    "title": "Promise直列実行",
    "problem": "tasks(関数配列)を順番に実行して結果配列を返す runSeries(tasks) を作ってください。",
    "level": "中級",
    "topic": "for...of + await",
    "duration": "14分",
    "starDifficulty": 2,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 113,
    "title": "startsWithで拡張子判定",
    "problem": "ファイル名が .png で終わるか返す isPng(filename) を作ってください。",
    "level": "初級",
    "topic": "startsWith + endsWith",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 114,
    "title": "先頭N件だけ取得",
    "problem": "配列の先頭n件を返す take(arr, n) を作ってください。",
    "level": "中級",
    "topic": "slice",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 115,
    "title": "空文字の除去",
    "problem": "文字列配列から空文字/空白のみ要素を除去する compactStrings(items) を作ってください。",
    "level": "初級",
    "topic": "filter + trim",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 116,
    "title": "オブジェクトキーの並び替え",
    "problem": "objのキーを昇順に並べた配列を返す sortedKeys(obj) を作ってください。",
    "level": "中級",
    "topic": "Object.keys + sort",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 117,
    "title": "最小/最大の同時取得",
    "problem": "numbers配列のmin/maxを返す getRange(numbers) を作ってください。",
    "level": "初級",
    "topic": "Math.min + Math.max",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 118,
    "title": "文字列テンプレート置換",
    "problem": "テンプレート内の {name} を実名へ置換する renderName(template, name) を作ってください。",
    "level": "中級",
    "topic": "replaceAll",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 119,
    "title": "ランダム整数生成",
    "problem": "min以上max以下の整数を返す randomInt(min, max) を作ってください。",
    "level": "初級",
    "topic": "Math.random",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 120,
    "title": "APIレスポンスok判定ヘルパー",
    "problem": "res.okならjsonを返し、そうでなければnullを返す readIfOk(res) を作ってください。",
    "level": "中級",
    "topic": "ternary + optional chaining",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 121,
    "title": "OR条件で検索",
    "problem": "titleまたはbodyにkeywordを含む要素だけ返す searchPosts(posts, keyword) を作ってください。",
    "level": "初級",
    "topic": "filter + includes",
    "duration": "8分",
    "starDifficulty": 2,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 122,
    "title": "数値レンジ正規化",
    "problem": "min,maxの順が逆でも [small, large] を返す normalizeRange(min, max) を作ってください。",
    "level": "中級",
    "topic": "Math.min + Math.max",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 123,
    "title": "改行区切りリスト化",
    "problem": "改行テキストを行配列にする toLines(text) を作ってください。",
    "level": "初級",
    "topic": "split",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 124,
    "title": "空配列でも平均値計算",
    "problem": "numbersの平均を返し、空配列なら0を返す averageOrZero(numbers) を作ってください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 125,
    "title": "先頭文字だけ大文字化",
    "problem": "文字列の先頭だけ大文字にする capitalize(text) を作ってください。",
    "level": "初級",
    "topic": "slice + toUpperCase",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 126,
    "title": "重み付き合計",
    "problem": "itemsの amount * weight を合計する weightedTotal(items) を作ってください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 127,
    "title": "先頭一致の真偽判定",
    "problem": "pathが\"/admin\"で始まるか返す isAdminPath(path) を作ってください。",
    "level": "初級",
    "topic": "startsWith",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 128,
    "title": "2配列の共通要素",
    "problem": "aとbの共通要素を返す intersect(a, b) を作ってください。",
    "level": "中級",
    "topic": "filter + Set",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 129,
    "title": "配列先頭の安全取得",
    "problem": "配列先頭要素を返し、空ならnullを返す firstOrNull(arr) を作ってください。",
    "level": "初級",
    "topic": "at",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 130,
    "title": "日付の新しい順ソート",
    "problem": "itemsをupdatedAtの新しい順で並べる sortByUpdated(items) を作ってください。",
    "level": "中級",
    "topic": "sort + Date",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 131,
    "title": "前後空白の統一除去",
    "problem": "配列内の各文字列をtrimした新配列を返す trimAll(items) を作ってください。",
    "level": "初級",
    "topic": "trim",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 132,
    "title": "数値文字列だけ抽出",
    "problem": "文字列配列から数値へ変換できる要素だけ返す pickNumericStrings(values) を作ってください。",
    "level": "中級",
    "topic": "filter + Number",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 133,
    "title": "偶数だけ抽出",
    "problem": "numbers配列から偶数だけ返す evenNumbers(numbers) を作ってください。",
    "level": "初級",
    "topic": "filter",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 134,
    "title": "URL末尾スラッシュ除去",
    "problem": "URL末尾の\"/\"だけ取り除く stripTrailingSlash(url) を作ってください。",
    "level": "中級",
    "topic": "replace",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 135,
    "title": "インデックス付きラベル作成",
    "problem": "itemsを \"1. xxx\" 形式へ変換する toIndexedLabels(items) を作ってください。",
    "level": "初級",
    "topic": "map",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 136,
    "title": "エラー再試行ラッパー",
    "problem": "fnを最大retries回まで試行する retry(fn, retries) を作ってください。",
    "level": "中級",
    "topic": "for + try/catch",
    "duration": "14分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 137,
    "title": "配列結合文字列生成",
    "problem": "tags配列を \", \" 区切り文字列へ変換する joinTags(tags) を作ってください。",
    "level": "初級",
    "topic": "join",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 138,
    "title": "先頭一致の高速判定集合",
    "problem": "prefixesのどれかでtextが始まるか判定する startsWithAny(text, prefixes) を作ってください。",
    "level": "中級",
    "topic": "some",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 139,
    "title": "0埋め時刻フォーマット",
    "problem": "h,m から HH:MM 文字列を返す formatTime(h, m) を作ってください。",
    "level": "初級",
    "topic": "padStart",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 140,
    "title": "ページ情報計算",
    "problem": "totalとpageSizeからtotalPagesを返す calcTotalPages(total, pageSize) を作ってください。",
    "level": "中級",
    "topic": "Math.ceil",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 141,
    "title": "URLオブジェクトでhost取得",
    "problem": "URL文字列からhostnameを返す getHost(url) を作ってください。",
    "level": "初級",
    "topic": "URL",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 142,
    "title": "配列をオブジェクト化",
    "problem": "users配列を id をキーにした辞書へ変換する indexById(users) を作ってください。",
    "level": "中級",
    "topic": "Object.fromEntries",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 143,
    "title": "配列生成ユーティリティ",
    "problem": "1..n の連番配列を作る createRange(n) を作ってください。",
    "level": "初級",
    "topic": "Array.from",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 144,
    "title": "deep copyの安全作成",
    "problem": "objの深いコピーを返す cloneDeep(obj) を作ってください。",
    "level": "中級",
    "topic": "structuredClone",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 145,
    "title": "存在しない値を除外",
    "problem": "配列から null と undefined を除外する compactNullish(values) を作ってください。",
    "level": "初級",
    "topic": "filter",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 146,
    "title": "安全な整数判定",
    "problem": "idが安全な整数か返す isSafeId(id) を作ってください。",
    "level": "中級",
    "topic": "Number.isSafeInteger",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 147,
    "title": "文字列反転",
    "problem": "文字列を反転して返す reverseText(text) を作ってください。",
    "level": "初級",
    "topic": "split + reverse + join",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 148,
    "title": "Promise.raceで先着取得",
    "problem": "複数Promiseの先に完了した値を返す firstResolved(promises) を作ってください。",
    "level": "中級",
    "topic": "Promise.race",
    "duration": "12分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 149,
    "title": "末尾n文字取得",
    "problem": "文字列の末尾n文字を返す tail(text, n) を作ってください。",
    "level": "初級",
    "topic": "slice",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 150,
    "title": "TTL有効期限判定",
    "problem": "savedAtとttlMsから期限切れか判定する isExpired(savedAt, ttlMs) を作ってください。",
    "level": "中級",
    "topic": "Date.now",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 151,
    "title": "文字列配列を小文字化",
    "problem": "文字列配列をすべて小文字へ変換する lowerAll(words) を作ってください。",
    "level": "初級",
    "topic": "map + toLowerCase",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 152,
    "title": "バッチ送信ペイロード作成",
    "problem": "ids配列を { id } 配列へ変換する toBatchPayload(ids) を作ってください。",
    "level": "中級",
    "topic": "map",
    "duration": "10分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 153,
    "title": "ISO日時の時刻だけ取得",
    "problem": "ISO文字列から HH:MM:SS を返す extractTime(iso) を作ってください。",
    "level": "初級",
    "topic": "split",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 154,
    "title": "map値の合計",
    "problem": "Map<number>の値合計を返す sumMapValues(map) を作ってください。",
    "level": "中級",
    "topic": "Map + reduce",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 155,
    "title": "先頭一致件数カウント",
    "problem": "prefixで始まる文字列の件数を返す countByPrefix(items, prefix) を作ってください。",
    "level": "初級",
    "topic": "filter + startsWith",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 156,
    "title": "全要素ユニーク判定",
    "problem": "配列に重複がないか判定する isUniqueArray(arr) を作ってください。",
    "level": "中級",
    "topic": "Set",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 157,
    "title": "固定小数点表示",
    "problem": "数値を小数2桁文字列へ変換する to2Decimal(value) を作ってください。",
    "level": "初級",
    "topic": "toFixed",
    "duration": "8分",
    "starDifficulty": 3,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 158,
    "title": "既定値マージ",
    "problem": "defaultsをbaseにしてoptionsを上書きする mergeOptions(defaults, options) を作ってください。",
    "level": "中級",
    "topic": "spread",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 159,
    "title": "先頭一致削除",
    "problem": "文字列先頭の\"#\"を1つ除去する stripHash(text) を作ってください。",
    "level": "初級",
    "topic": "replace",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 160,
    "title": "実行結果をResult型化",
    "problem": "fn実行結果を { ok, value/error } で返す toResult(fn) を作ってください。",
    "level": "中級",
    "topic": "try/catch",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 161,
    "title": "mapで配送ラベル生成",
    "problem": "orders配列から `#注文ID-顧客名` 形式のラベル配列を作ってください。",
    "level": "初級",
    "topic": "map",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 162,
    "title": "mapで通貨換算",
    "problem": "pricesを通貨レートで円換算し、整数へ丸めた配列を返してください。",
    "level": "中級",
    "topic": "map",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 163,
    "title": "filterで平日のみ抽出",
    "problem": "day配列から土日を除外した配列を返してください。",
    "level": "初級",
    "topic": "filter",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 164,
    "title": "filterで異常値検知",
    "problem": "センサー値配列から閾値upperを超えた値だけ返してください。",
    "level": "中級",
    "topic": "filter",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 165,
    "title": "findで未払い請求を1件取得",
    "problem": "invoicesから status が \"unpaid\" の最初の要素を返してください。",
    "level": "初級",
    "topic": "find",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 166,
    "title": "findで期限切れチケット検索",
    "problem": "ticketsから dueAt が now より前の最初の要素を返してください。",
    "level": "中級",
    "topic": "find",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 167,
    "title": "reduceで数量合計",
    "problem": "cart配列の qty を合計して返してください。",
    "level": "初級",
    "topic": "reduce",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 168,
    "title": "reduceで月別売上集計",
    "problem": "ordersを month(\"YYYY-MM\") ごとの売上合計オブジェクトへ集計してください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 169,
    "title": "includesで権限判定",
    "problem": "roles配列に\"admin\"が含まれるか返してください。",
    "level": "初級",
    "topic": "includes",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 170,
    "title": "includesで拒否ドメイン判定",
    "problem": "emailのドメインがdenyListに含まれるか判定してください。",
    "level": "中級",
    "topic": "includes",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 171,
    "title": "Object.keysで項目数取得",
    "problem": "オブジェクトのキー数を返す countFields(obj) を作ってください。",
    "level": "初級",
    "topic": "Object.keys",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 172,
    "title": "Object.valuesで最大値取得",
    "problem": "scoreMapオブジェクトの最大スコアを返してください。",
    "level": "中級",
    "topic": "Object.values",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 173,
    "title": "スプレッドで配列追加",
    "problem": "tags配列の末尾にnewTagを追加した新配列を返してください。",
    "level": "初級",
    "topic": "...spread",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 174,
    "title": "スプレッドで条件付き上書き",
    "problem": "isAdminがtrueの時だけ role: \"admin\" を付与する buildUser(base, isAdmin) を作ってください。",
    "level": "中級",
    "topic": "...spread",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 175,
    "title": "async/awaitで1件取得",
    "problem": "getProfile() をawaitして profile.name を返す getProfileName() を作ってください。",
    "level": "初級",
    "topic": "async/await",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 176,
    "title": "async/awaitで逐次処理",
    "problem": "idsを順番にfetchUserByIdして結果配列を返す loadUsersInOrder(ids) を作ってください。",
    "level": "中級",
    "topic": "async/await",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 177,
    "title": "fetchでGET + json",
    "problem": "urlを受けてJSONを返す simpleGet(url) を作ってください。",
    "level": "初級",
    "topic": "fetch",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 178,
    "title": "fetchでPATCH送信",
    "problem": "idとpatchを受け取りPATCHで更新する patchUser(id, patch) を作ってください。",
    "level": "中級",
    "topic": "fetch",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 179,
    "title": "JSON.stringifyで保存文字列化",
    "problem": "settingsオブジェクトをlocalStorage保存向け文字列へ変換する serializeSettings を作ってください。",
    "level": "初級",
    "topic": "JSON.stringify",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 180,
    "title": "JSON.parseで配列検証",
    "problem": "json文字列を配列として復元し、配列でなければ空配列を返す parseArrayOrEmpty を作ってください。",
    "level": "中級",
    "topic": "JSON.parse",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 181,
    "title": "mapで通知文面を生成",
    "problem": "notifications配列から `【type】message` 形式の文字列配列を返す formatNotifications(notifications) を作ってください。",
    "level": "初級",
    "topic": "map",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 182,
    "title": "filterで公開記事だけ抽出",
    "problem": "posts配列から status が \"published\" の記事だけ返す getPublishedPosts(posts) を作ってください。",
    "level": "中級",
    "topic": "filter",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 183,
    "title": "findで現在ログインユーザー取得",
    "problem": "users配列から isCurrent が true のユーザーを返す getCurrentUser(users) を作ってください。",
    "level": "初級",
    "topic": "find",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 184,
    "title": "reduceでタグ別件数を集計",
    "problem": "articles配列から tag ごとの件数オブジェクトを返す countByTag(articles) を作ってください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 185,
    "title": "includesで権限判定",
    "problem": "roles配列に \"admin\" が含まれるか返す canAccessAdmin(roles) を作ってください。",
    "level": "初級",
    "topic": "includes",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 186,
    "title": "Object.keysで差分フィールド抽出",
    "problem": "before/afterオブジェクトを比較し、値が変わったキー配列を返す getChangedFields(before, after) を作ってください。",
    "level": "中級",
    "topic": "Object.keys",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 187,
    "title": "Object.valuesで在庫合計",
    "problem": "inventoryオブジェクトの値を合計して返す getTotalStock(inventory) を作ってください。",
    "level": "初級",
    "topic": "Object.values",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 188,
    "title": "スプレッドでクエリ条件マージ",
    "problem": "baseQueryにoverridesを上書きマージして返す buildQuery(baseQuery, overrides) を作ってください。",
    "level": "中級",
    "topic": "...spread",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 189,
    "title": "async/awaitで2API直列取得",
    "problem": "userIdを受けて user と profile を順に取得し { user, profile } を返す fetchUserBundle(userId) を作ってください。",
    "level": "初級",
    "topic": "async/await + fetch",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 190,
    "title": "JSON.parse/stringifyで安全更新",
    "problem": "json文字列の設定を更新して再度文字列で返す updateSettingsJson(settingsJson, patch) を作ってください。parse失敗時はpatchのみを文字列化して返します。",
    "level": "中級",
    "topic": "JSON.parse + JSON.stringify",
    "duration": "12分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 191,
    "title": "mapで商品名一覧を整形",
    "problem": "products配列から `#id name` 形式の文字列配列を返す formatProductNames(products) を作ってください。",
    "level": "初級",
    "topic": "map",
    "duration": "8分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 192,
    "title": "mapでAPIレスポンスをUI型へ変換",
    "problem": "users配列を `{ label, value }` 形式へ変換する toSelectOptions(users) を作ってください。labelはname、valueはidです。",
    "level": "中級",
    "topic": "map",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 193,
    "title": "filterで期限切れクーポン除外",
    "problem": "coupons配列から expired が false の要素のみ返す getAvailableCoupons(coupons) を作ってください。",
    "level": "初級",
    "topic": "filter",
    "duration": "10分",
    "starDifficulty": 4,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 194,
    "title": "filterで価格帯検索",
    "problem": "items配列から minPrice以上maxPrice以下の要素を返す filterByPriceRange(items, minPrice, maxPrice) を作ってください。",
    "level": "中級",
    "topic": "filter",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 195,
    "title": "findで最初の未完了タスク取得",
    "problem": "tasks配列から done が false の最初の要素を返す getFirstPendingTask(tasks) を作ってください。",
    "level": "初級",
    "topic": "find",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 196,
    "title": "findでSKU一致アイテム取得",
    "problem": "catalog配列とskuを受け取り、一致する商品を返す findBySku(catalog, sku) を作ってください。",
    "level": "中級",
    "topic": "find",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 197,
    "title": "reduceで注文点数を合計",
    "problem": "orderItems配列のqtyを合計して返す countOrderItems(orderItems) を作ってください。",
    "level": "初級",
    "topic": "reduce",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 198,
    "title": "reduceでユーザーをID辞書化",
    "problem": "users配列を `{ [id]: user }` の形に変換する indexUsersById(users) を作ってください。",
    "level": "中級",
    "topic": "reduce",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 199,
    "title": "includesで拡張子許可判定",
    "problem": "allowedExtensions配列にextが含まれるか判定する isAllowedExtension(allowedExtensions, ext) を作ってください。",
    "level": "初級",
    "topic": "includes",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 200,
    "title": "includesで危険語チェック",
    "problem": "textに禁止ワード配列のいずれかが含まれるか返す containsBlockedWord(text, blockedWords) を作ってください。",
    "level": "中級",
    "topic": "includes",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 201,
    "title": "Object.keysで空オブジェクト判定",
    "problem": "objが空オブジェクトならtrueを返す isEmptyObject(obj) を作ってください。",
    "level": "初級",
    "topic": "Object.keys",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 202,
    "title": "Object.keysで必須項目不足を検出",
    "problem": "payloadとrequiredKeysを受け取り、欠けているキー配列を返す getMissingKeys(payload, requiredKeys) を作ってください。",
    "level": "中級",
    "topic": "Object.keys",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 203,
    "title": "Object.valuesで平均評価を計算",
    "problem": "ratingsオブジェクトの平均値を返す calcAverageRating(ratings) を作ってください。値が0件なら0を返します。",
    "level": "初級",
    "topic": "Object.values",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 204,
    "title": "Object.valuesで売上上位判定",
    "problem": "salesMapの最大売上を返す getMaxSales(salesMap) を作ってください。データがなければ0を返します。",
    "level": "中級",
    "topic": "Object.values",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 205,
    "title": "スプレッドで配列先頭に追加",
    "problem": "items配列の先頭にnewItemを追加した新配列を返す prependItem(items, newItem) を作ってください。",
    "level": "初級",
    "topic": "...spread",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 206,
    "title": "スプレッドでネスト設定を更新",
    "problem": "settingsのnotifications.emailだけをnewValueで更新する updateEmailNotification(settings, newValue) を作ってください。",
    "level": "中級",
    "topic": "...spread",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 207,
    "title": "async/awaitで商品詳細取得",
    "problem": "productIdを受けて `/api/products/:id` からJSONを返す fetchProduct(productId) を作ってください。",
    "level": "初級",
    "topic": "async/await + fetch",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 208,
    "title": "async/awaitでレスポンス状態検証",
    "problem": "urlを受けてGETし、res.okがfalseならErrorをthrow、trueならJSONを返す fetchOrThrow(url) を作ってください。",
    "level": "中級",
    "topic": "async/await + fetch",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 209,
    "title": "fetchでJSON POST送信",
    "problem": "payloadを `/api/contact` にPOSTし、JSONレスポンスを返す sendContact(payload) を作ってください。",
    "level": "初級",
    "topic": "fetch",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 210,
    "title": "fetchでクエリ付き検索",
    "problem": "keywordをクエリにつけて `/api/search` を呼び出しJSONを返す searchByKeyword(keyword) を作ってください。",
    "level": "中級",
    "topic": "fetch",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 211,
    "title": "JSON.parseで文字列配列復元",
    "problem": "jsonTextを配列として復元する parseStringList(jsonText) を作ってください。失敗時は空配列を返します。",
    "level": "初級",
    "topic": "JSON.parse",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 212,
    "title": "JSON.parseで設定の型を補正",
    "problem": "jsonTextをparseし、themeが文字列でなければ\"light\"を設定して返す parseConfigWithTheme(jsonText) を作ってください。",
    "level": "中級",
    "topic": "JSON.parse",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 213,
    "title": "JSON.stringifyでクエリキャッシュキー作成",
    "problem": "paramsオブジェクトからキャッシュキー文字列を返す createCacheKey(params) を作ってください。",
    "level": "初級",
    "topic": "JSON.stringify",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 214,
    "title": "JSON.stringifyで監査ログ行を作成",
    "problem": "action, actorId, payloadを受けて監査ログJSON文字列を返す buildAuditLog(action, actorId, payload) を作ってください。timestampはDate.now()を使います。",
    "level": "中級",
    "topic": "JSON.stringify",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 215,
    "title": "map+includesで選択状態を付与",
    "problem": "items配列とselectedIds配列を受け取り、各要素に selected(boolean) を追加した配列を返す addSelectedFlag(items, selectedIds) を作ってください。",
    "level": "初級",
    "topic": "map + includes",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 216,
    "title": "filter+mapで公開タイトル一覧化",
    "problem": "posts配列から公開済みのみ抽出し、タイトル配列を返す listPublishedTitles(posts) を作ってください。",
    "level": "中級",
    "topic": "filter + map",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 217,
    "title": "reduce+Object.valuesで平均注文額",
    "problem": "orderAmountMapの平均値を返す calcAverageOrderAmount(orderAmountMap) を作ってください。データがない場合は0を返します。",
    "level": "初級",
    "topic": "reduce + Object.values",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 218,
    "title": "async/awaitで並列取得統合",
    "problem": "dashboardデータとして `/api/stats` と `/api/alerts` を並列取得し `{ stats, alerts }` を返す fetchDashboardData() を作ってください。",
    "level": "中級",
    "topic": "async/await + fetch",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 219,
    "title": "JSON.parse+includesでお気に入り判定",
    "problem": "favoritesJson(配列JSON)とitemIdを受け取り、含まれていればtrueを返す isFavoriteFromJson(favoritesJson, itemId) を作ってください。失敗時はfalseです。",
    "level": "初級",
    "topic": "JSON.parse + includes",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 220,
    "title": "Object.keys+reduceで空値キー抽出",
    "problem": "formオブジェクトから値が空文字のキー配列を返す listBlankFields(form) を作ってください。",
    "level": "中級",
    "topic": "Object.keys + reduce",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 221,
    "title": "Regexで数字のみ判定",
    "problem": "文字列が半角数字のみで構成されるか判定する isDigitsOnly(text) を作ってください。空文字はfalseです。",
    "level": "初級",
    "topic": "RegExp",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 222,
    "title": "Regexで英数字ID検証",
    "problem": "6〜12文字の英数字のみ許可する validateUserId(userId) を作ってください。",
    "level": "初級",
    "topic": "RegExp validation",
    "duration": "10分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 223,
    "title": "メール形式バリデーション",
    "problem": "メールアドレス形式を簡易判定する isValidEmail(email) を作ってください。",
    "level": "中級",
    "topic": "RegExp validation",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 224,
    "title": "電話番号のハイフン許容判定",
    "problem": "090-1234-5678 または 09012345678 形式を許可する isValidPhone(phone) を作ってください。",
    "level": "中級",
    "topic": "RegExp validation",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 225,
    "title": "郵便番号フォーマット判定",
    "problem": "123-4567 形式のみ許可する isValidZip(zip) を作ってください。",
    "level": "初級",
    "topic": "RegExp",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 226,
    "title": "パスワード強度チェック",
    "problem": "8文字以上で英字と数字を含むか判定する isStrongPassword(password) を作ってください。",
    "level": "中級",
    "topic": "RegExp validation",
    "duration": "14分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 227,
    "title": "URL形式の簡易判定",
    "problem": "http:// または https:// で始まるURLを判定する isHttpUrl(url) を作ってください。",
    "level": "中級",
    "topic": "RegExp validation",
    "duration": "12分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 228,
    "title": "バリデーションエラー収集",
    "problem": "form({ email, phone, zip })を受け取り、不正項目名の配列を返す validateContactForm(form) を作ってください。",
    "level": "実務",
    "topic": "RegExp form validation",
    "duration": "16分",
    "starDifficulty": 5,
    "mutationWarningShort": "破壊的操作あり",
    "mutationWarningLevel": "high"
  },
  {
    "id": 229,
    "title": "入力から数字だけ抽出",
    "problem": "文字列から数字以外を除去して返す extractDigits(text) を作ってください。",
    "level": "初級",
    "topic": "RegExp replace",
    "duration": "8分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  },
  {
    "id": 230,
    "title": "複数行メッセージの禁止語検知",
    "problem": "text内に禁止語(spam, scam)が大文字小文字無視で含まれるか返す hasBlockedWords(text) を作ってください。",
    "level": "実務",
    "topic": "RegExp flags",
    "duration": "15分",
    "starDifficulty": 5,
    "mutationWarningShort": null,
    "mutationWarningLevel": null
  }
]
